### ISSUE TITLE
serve multiple artifacts?

### ISSUE THREAD

**Issue by IntranetFactory** [claudio-silva/claude-artifact-runner#9]
I made a version which can serve multiple artifacts from a new src\artifacts folder https://github.com/IntranetFactory/claude-artifacts-runner/tree/routes/src/artifacts

Please let me know if I should create a PR for that.

**Comment by claudio-silva** [comment]
Hi @IntranetFactory, thanks for your proposal.

I installed your version and tested your demo components. I think it's a good idea, as it gives the developer more flexibility and can even create a simple multipage app just by linking from one page to another. Each page could be generated independently by Claude on its website and dropped into the artifacts folder. I like it 😃

If you would like to submit a PR, please include instructions in the Readme on how to view the artifacts in the browser, as the user will probably have no idea what the predefined routes are.

Better yet, how about replacing the default component with a page that has links to the other demo components?

The Readme instructions on how to include a new artifact should be changed too.

If you don't have the time to make these changes, you can submit what you have, and I'll take it from there.

**Comment by claudio-silva** [comment]
Hi @IntranetFactory,

It's been over a month, so I assume you either forgot about this or haven't had the time to create the pull request.

I recently found some free time to dive into this project, so I decided to proceed and merge it myself. I used your routing code but opted for a simpler two-page demo instead of your demo components. The goal is to demonstrate functionality and navigation between components, and the provided code will ultimately be replaced by the developer, so it's not necessary to add many demo components.

Thank you for proposing this enhancement; it saved me time. I've added an acknowledgment for your contribution in the Acknowledgements section.

Best regards,
Cláudio

**Comment by IntranetFactory** [comment]
I'm sorry, I forgot to create the PR. I also continued - and added options to user other LLMs (like OpenAI) to generate artifacts and to edit the generated React  https://claude-artifacts-runner.pages.dev/  https://github.com/IntranetFactory/claude-artifacts-runner

**Comment by claudio-silva** [comment]
I'm glad to hear that this project was useful for your component generator. It's a great idea, but since it falls outside the scope of this project, which focuses on Claude Artifacts, it makes sense to develop it as a separate project.

I'm also working on some similar ideas and will be publishing them as separate projects. 

Good luck with your work!
